# Generated by Django 3.1.6 on 2021-02-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('given_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=64)),
                ('time_zone', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Activity_Periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=64)),
                ('end_time', models.CharField(max_length=64)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='json_api.user')),
            ],
        ),
    ]
